/* Generated by dx imports sync. */
/* Source-owned IDE contract for DX WWW auto-imports. */

declare module "#components" {
  export { Icon } from "../../components/icons/icon";
}

declare module "#imports" {
  export { Icon } from "../../components/icons/icon";
}

declare global {
  const Icon: typeof import("../../components/icons/icon")["Icon"];
}

export {};
