export type FormulaFunctionCategory =
  | "Compatibility"
  | "Cube"
  | "Date and time"
  | "Engineering"
  | "Financial"
  | "Information"
  | "Logical"
  | "Lookup and reference"
  | "Math"
  | "Statistical"
  | "Text"
  | "Web";

export type FormulaFunctionSuggestion = {
  category: FormulaFunctionCategory;
  name: string;
  signature: string;
};

export const formulaFunctions = [
  { category: "Math", name: "SUM", signature: "SUM(number1, number2)" },
  { category: "Math", name: "SUMIF", signature: "SUMIF(range, criteria, sum_range)" },
  { category: "Math", name: "SUMIFS", signature: "SUMIFS(sum_range, criteria_range1, criteria1)" },
  { category: "Math", name: "ROUND", signature: "ROUND(number, digits)" },
  { category: "Math", name: "ROUNDUP", signature: "ROUNDUP(number, digits)" },
  { category: "Math", name: "ROUNDDOWN", signature: "ROUNDDOWN(number, digits)" },
  { category: "Math", name: "ABS", signature: "ABS(number)" },
  { category: "Math", name: "INT", signature: "INT(number)" },
  { category: "Math", name: "MOD", signature: "MOD(number, divisor)" },
  { category: "Math", name: "POWER", signature: "POWER(number, power)" },
  { category: "Math", name: "SQRT", signature: "SQRT(number)" },
  { category: "Math", name: "PRODUCT", signature: "PRODUCT(number1, number2)" },
  { category: "Math", name: "SUBTOTAL", signature: "SUBTOTAL(function_num, ref1)" },
  { category: "Math", name: "AGGREGATE", signature: "AGGREGATE(function_num, options, ref1)" },
  { category: "Statistical", name: "AVERAGE", signature: "AVERAGE(number1, number2)" },
  { category: "Statistical", name: "AVERAGEIF", signature: "AVERAGEIF(range, criteria, average_range)" },
  { category: "Statistical", name: "COUNT", signature: "COUNT(value1, value2)" },
  { category: "Statistical", name: "COUNTA", signature: "COUNTA(value1, value2)" },
  { category: "Statistical", name: "COUNTIF", signature: "COUNTIF(range, criteria)" },
  { category: "Statistical", name: "COUNTIFS", signature: "COUNTIFS(criteria_range1, criteria1)" },
  { category: "Statistical", name: "MAX", signature: "MAX(number1, number2)" },
  { category: "Statistical", name: "MIN", signature: "MIN(number1, number2)" },
  { category: "Statistical", name: "MEDIAN", signature: "MEDIAN(number1, number2)" },
  { category: "Statistical", name: "STDEV.S", signature: "STDEV.S(number1, number2)" },
  { category: "Statistical", name: "NORM.S.DIST", signature: "NORM.S.DIST(z, cumulative)" },
  { category: "Statistical", name: "NORM.S.INV", signature: "NORM.S.INV(probability)" },
  { category: "Logical", name: "IF", signature: "IF(test, value_if_true, value_if_false)" },
  { category: "Logical", name: "IFS", signature: "IFS(test1, value1, test2, value2)" },
  { category: "Logical", name: "AND", signature: "AND(logical1, logical2)" },
  { category: "Logical", name: "OR", signature: "OR(logical1, logical2)" },
  { category: "Logical", name: "NOT", signature: "NOT(logical)" },
  { category: "Logical", name: "XOR", signature: "XOR(logical1, logical2)" },
  { category: "Logical", name: "IFERROR", signature: "IFERROR(value, value_if_error)" },
  { category: "Logical", name: "IFNA", signature: "IFNA(value, value_if_na)" },
  { category: "Logical", name: "SWITCH", signature: "SWITCH(expression, value1, result1)" },
  { category: "Logical", name: "LET", signature: "LET(name1, value1, calculation)" },
  { category: "Logical", name: "LAMBDA", signature: "LAMBDA(parameter1, calculation)" },
  { category: "Text", name: "CONCAT", signature: "CONCAT(text1, text2)" },
  { category: "Text", name: "CONCATENATE", signature: "CONCATENATE(text1, text2)" },
  { category: "Text", name: "TEXTJOIN", signature: "TEXTJOIN(delimiter, ignore_empty, text1)" },
  { category: "Text", name: "LEFT", signature: "LEFT(text, num_chars)" },
  { category: "Text", name: "RIGHT", signature: "RIGHT(text, num_chars)" },
  { category: "Text", name: "MID", signature: "MID(text, start_num, num_chars)" },
  { category: "Text", name: "LEN", signature: "LEN(text)" },
  { category: "Text", name: "LOWER", signature: "LOWER(text)" },
  { category: "Text", name: "UPPER", signature: "UPPER(text)" },
  { category: "Text", name: "PROPER", signature: "PROPER(text)" },
  { category: "Text", name: "TRIM", signature: "TRIM(text)" },
  { category: "Text", name: "TEXT", signature: "TEXT(value, format_text)" },
  { category: "Text", name: "VALUE", signature: "VALUE(text)" },
  { category: "Text", name: "SUBSTITUTE", signature: "SUBSTITUTE(text, old_text, new_text)" },
  { category: "Text", name: "SEARCH", signature: "SEARCH(find_text, within_text)" },
  { category: "Text", name: "FIND", signature: "FIND(find_text, within_text)" },
  { category: "Date and time", name: "TODAY", signature: "TODAY()" },
  { category: "Date and time", name: "NOW", signature: "NOW()" },
  { category: "Date and time", name: "DATE", signature: "DATE(year, month, day)" },
  { category: "Date and time", name: "TIME", signature: "TIME(hour, minute, second)" },
  { category: "Date and time", name: "DAY", signature: "DAY(serial_number)" },
  { category: "Date and time", name: "MONTH", signature: "MONTH(serial_number)" },
  { category: "Date and time", name: "YEAR", signature: "YEAR(serial_number)" },
  { category: "Date and time", name: "WEEKDAY", signature: "WEEKDAY(serial_number, return_type)" },
  { category: "Date and time", name: "ISOWEEKNUM", signature: "ISOWEEKNUM(date)" },
  { category: "Date and time", name: "DAYS", signature: "DAYS(end_date, start_date)" },
  { category: "Date and time", name: "DATEDIF", signature: "DATEDIF(start_date, end_date, unit)" },
  { category: "Date and time", name: "EOMONTH", signature: "EOMONTH(start_date, months)" },
  { category: "Date and time", name: "NETWORKDAYS", signature: "NETWORKDAYS(start_date, end_date, holidays)" },
  { category: "Date and time", name: "WORKDAY", signature: "WORKDAY(start_date, days, holidays)" },
  { category: "Lookup and reference", name: "VLOOKUP", signature: "VLOOKUP(value, table, index, exact)" },
  { category: "Lookup and reference", name: "HLOOKUP", signature: "HLOOKUP(value, table, row_index, exact)" },
  { category: "Lookup and reference", name: "XLOOKUP", signature: "XLOOKUP(value, lookup_array, return_array, if_not_found)" },
  { category: "Lookup and reference", name: "XMATCH", signature: "XMATCH(value, lookup_array, match_mode, search_mode)" },
  { category: "Lookup and reference", name: "MATCH", signature: "MATCH(value, lookup_array, match_type)" },
  { category: "Lookup and reference", name: "INDEX", signature: "INDEX(array, row_num, column_num)" },
  { category: "Lookup and reference", name: "CHOOSE", signature: "CHOOSE(index_num, value1, value2)" },
  { category: "Lookup and reference", name: "CHOOSECOLS", signature: "CHOOSECOLS(array, col_num1)" },
  { category: "Lookup and reference", name: "CHOOSEROWS", signature: "CHOOSEROWS(array, row_num1)" },
  { category: "Lookup and reference", name: "DROP", signature: "DROP(array, rows, columns)" },
  { category: "Lookup and reference", name: "ROW", signature: "ROW(reference)" },
  { category: "Lookup and reference", name: "COLUMN", signature: "COLUMN(reference)" },
  { category: "Lookup and reference", name: "ROWS", signature: "ROWS(array)" },
  { category: "Lookup and reference", name: "COLUMNS", signature: "COLUMNS(array)" },
  { category: "Lookup and reference", name: "TAKE", signature: "TAKE(array, rows, columns)" },
  { category: "Financial", name: "PMT", signature: "PMT(rate, nper, pv, fv, type)" },
  { category: "Financial", name: "FV", signature: "FV(rate, nper, pmt, pv, type)" },
  { category: "Financial", name: "PV", signature: "PV(rate, nper, pmt, fv, type)" },
  { category: "Financial", name: "NPER", signature: "NPER(rate, pmt, pv, fv, type)" },
  { category: "Financial", name: "RATE", signature: "RATE(nper, pmt, pv, fv, type)" },
  { category: "Financial", name: "NPV", signature: "NPV(rate, value1, value2)" },
  { category: "Financial", name: "IRR", signature: "IRR(values, guess)" },
  { category: "Financial", name: "MIRR", signature: "MIRR(values, finance_rate, reinvest_rate)" },
  { category: "Information", name: "ISBLANK", signature: "ISBLANK(value)" },
  { category: "Information", name: "ISERROR", signature: "ISERROR(value)" },
  { category: "Information", name: "ISERR", signature: "ISERR(value)" },
  { category: "Information", name: "ISNA", signature: "ISNA(value)" },
  { category: "Information", name: "ISNUMBER", signature: "ISNUMBER(value)" },
  { category: "Information", name: "ISTEXT", signature: "ISTEXT(value)" },
  { category: "Information", name: "ISFORMULA", signature: "ISFORMULA(reference)" },
  { category: "Information", name: "FORMULATEXT", signature: "FORMULATEXT(reference)" },
  { category: "Information", name: "SHEET", signature: "SHEET(value)" },
  { category: "Information", name: "SHEETS", signature: "SHEETS(value)" },
  { category: "Engineering", name: "BITAND", signature: "BITAND(number1, number2)" },
  { category: "Engineering", name: "BITOR", signature: "BITOR(number1, number2)" },
  { category: "Engineering", name: "BITXOR", signature: "BITXOR(number1, number2)" },
  { category: "Engineering", name: "BITLSHIFT", signature: "BITLSHIFT(number, shift_amount)" },
  { category: "Engineering", name: "BITRSHIFT", signature: "BITRSHIFT(number, shift_amount)" },
  { category: "Engineering", name: "BASE", signature: "BASE(number, radix, min_length)" },
  { category: "Engineering", name: "DECIMAL", signature: "DECIMAL(text, radix)" },
  { category: "Compatibility", name: "BETADIST", signature: "BETADIST(x, alpha, beta, cumulative)" },
  { category: "Compatibility", name: "NORMDIST", signature: "NORMDIST(x, mean, standard_dev, cumulative)" },
  { category: "Compatibility", name: "POISSON", signature: "POISSON(x, mean, cumulative)" },
  { category: "Compatibility", name: "WEIBULL", signature: "WEIBULL(x, alpha, beta, cumulative)" },
  { category: "Cube", name: "CUBEMEMBER", signature: "CUBEMEMBER(connection, member_expression, caption)" },
  { category: "Cube", name: "CUBESET", signature: "CUBESET(connection, set_expression, caption)" },
  { category: "Cube", name: "CUBESETCOUNT", signature: "CUBESETCOUNT(set)" },
  { category: "Cube", name: "CUBERANKEDMEMBER", signature: "CUBERANKEDMEMBER(connection, set_expression, rank, caption)" },
  { category: "Cube", name: "CUBEVALUE", signature: "CUBEVALUE(connection, member_expression1)" },
  { category: "Web", name: "ENCODEURL", signature: "ENCODEURL(text)" },
] as const satisfies readonly FormulaFunctionSuggestion[];
