/* Generated by dx imports sync. */
/* Source-owned IDE contract for DX WWW auto-imports. */

declare module "#components" {
  export { SearchControls } from "../../components/metasearch/search-controls";
  export { SearchToolbar } from "../../components/metasearch/search-toolbar";
  export { IconLabel } from "../../components/ui/icon-label";
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare module "#imports" {
  export { SearchControls } from "../../components/metasearch/search-controls";
  export { SearchToolbar } from "../../components/metasearch/search-toolbar";
  export { IconLabel } from "../../components/ui/icon-label";
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare global {
  const SearchControls: typeof import("../../components/metasearch/search-controls")["SearchControls"];
  const SearchToolbar: typeof import("../../components/metasearch/search-toolbar")["SearchToolbar"];
  const IconLabel: typeof import("../../components/ui/icon-label")["IconLabel"];
  const Icon: typeof import("../../components/icons/icon")["Icon"];
}

export {};
