import type { ProductCapability } from "@/lib/product/capability-types";

export const aiCapabilities = [
  {
    id: "ai-text-assistant",
    area: "ai",
    label: "AI edit assistant",
    userValue: "AI can draft scripts, captions, B-roll plans, video project blueprints, subtitle translations, repurpose plans, edit plans, and subtitle styles.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/app/api/ai/editor, src/lib/ai, src/app/settings/page.tsx",
    evidence: ["Vercel AI SDK", "Groq provider", "structured outputs", "usage logging", "generation history", "safety preflight", "subtitle translation"],
    nextStep: "Add richer image/audio editing provider adapters.",
  },
  {
    id: "ai-image-generation",
    area: "ai",
    label: "AI image generation and editing",
    userValue: "Generated and edited image assets can be previewed, imported, placed on the canvas, and guided by masks, outpaint presets, background cleanup, and translation controls when image-model support exists.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/ai/editor-ai.ts, src/features/editor/components/ai-assistant-panel.tsx, src/features/editor/components/ai-image-edit-controls.tsx",
    evidence: [
      "Image schema",
      "base64 validation",
      "source image validation",
      "AI SDK image prompt edits",
      "mask-based inpaint",
      "outpaint presets",
      "background removal mode",
      "image translation mode",
      "legal cleanup mode",
      "local transparent-background adapter",
      "offline background removal fallback",
      "import resilience",
      "generation records",
    ],
    nextStep: "Verify AI image generation with real owner-supplied providers and add richer local cleanup modes.",
  },
  {
    id: "smart-cut",
    area: "ai",
    label: "Smart cut",
    userValue: "AI can identify candidate cuts and apply accepted ranges to the timeline after review.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/ai/schemas.ts, src/lib/editor/timeline-cuts.ts, src/features/editor/components/ai-result-view.tsx",
    evidence: ["Finite time range validation", "smart-cut output contract", "review queue", "timeline cut apply command"],
    nextStep: "Add silence and filler-word detection that feeds this review queue.",
  },
  {
    id: "automatic-captions",
    area: "ai",
    label: "Automatic captions from media",
    userValue: "Imported audio or video should generate timed captions automatically.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/app/api/ai/transcribe, src/lib/ai/transcription.ts, src/features/editor/components/ai-assistant-panel.tsx",
    evidence: ["AI SDK transcription", "Groq Whisper", "media upload", "caption layer apply"],
    nextStep: "Add longer-media chunking, local fallback adapters, and post-transcription cleanup controls.",
  },
  {
    id: "applied-silence-removal",
    area: "ai",
    label: "Applied silence and filler-word removal",
    userValue: "AI cut suggestions should become real timeline edits after approval.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/editor/cleanup-cuts.ts, src/lib/editor/timeline-cuts.ts, src/features/editor/state/editor-timeline-edit-slice.ts",
    evidence: ["reviewed cut ranges", "undoable timeline apply command", "waveform silence suggestions", "filler-word transcript suggestions"],
    nextStep: "Add stronger dialogue analysis and manual threshold controls for cleanup proposals.",
  },
  {
    id: "ai-voice-dubbing",
    area: "ai",
    label: "AI voice, dubbing, and translation",
    userValue: "Creators can generate translated captions and turn longer scripts into one replaceable voiceover audio layer through provider-safe speech chunking.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/ai/speech.ts, src/app/api/ai/speech, src/features/editor/components/ai-assistant-panel.tsx",
    evidence: ["subtitle-translation output contract", "AI SDK speech", "Groq speech adapter", "long-script chunking", "concatenated WAV output", "replaceable audio layer"],
    nextStep: "Add full dubbing and real provider verification for long voiceover scripts.",
  },
  {
    id: "ai-video-generation",
    area: "ai",
    label: "AI clip, B-roll, and script-to-video generation",
    userValue: "AI can turn scripts, imported article/PDF text, embedded-OCR PDF text, screenshot/storyboard image sources, or pasted briefs into editable local projects, save short-form variants, insert reviewed B-roll, place stock scene media, generate scene image assets through the existing image model path, and place owner-supplied generated scene video clips when a connected service is configured.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/ai, src/lib/editor/ai-video-project.ts, src/lib/editor/ai-video-media-placement.ts, src/lib/editor/project-variants.ts, src/features/editor/components/ai-result-view.tsx",
    evidence: [
      "AI repurpose clips",
      "clip variants",
      "AI video project",
      "article text to video",
      "article/PDF source ingest",
      "embedded OCR PDF text extraction",
      "image source to video project",
      "AI Gateway vision model routing",
      "local project save",
      "B-roll review",
      "stock media insertion",
      "generated scene media placement",
      "generated scene image placement",
      "generated scene video placement",
      "owner-supplied scene video adapter",
      "partial scene image failure recovery",
      "partial scene video failure recovery",
    ],
    nextStep: "Verify generated scene videos with real owner-supplied providers and add stronger cross-provider fallbacks when free adapters exist.",
  },
  {
    id: "ai-media-cleanup",
    area: "ai",
    label: "AI media cleanup",
    userValue: "Creators can save cleaned audio layers with selectable local noise reduction, voice isolation, room echo reduction, speech enhancement modes, adjustable cleanup strength, before/after preview controls, an optional connected audio restoration service, and optional connected video enhancement for stabilization, eye-contact, and lip-sync.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/audio/cleanup.ts, src/lib/audio/cleanup-contract.ts, src/lib/ai/audio-restoration.ts, src/lib/ai/video-enhancement.ts, src/app/api/ai/audio-restoration, src/app/api/ai/video-enhancement, src/app/api/ai/audio-cleanup, src/features/editor/components/ai-audio-cleanup-controls.tsx, src/features/editor/components/ai-video-enhancement-controls.tsx",
    evidence: [
      "local noise reduction adapter",
      "local voice isolation adapter",
      "local room echo reduction adapter",
      "local speech enhancement adapter",
      "optional connected restoration service",
      "optional connected video enhancement service",
      "stabilization service mode",
      "eye-contact service mode",
      "lip-sync service mode",
      "adjustable cleanup strength",
      "saved before/after asset",
      "preview controls",
      "generation history",
      "usage safety record",
    ],
    nextStep: "Verify connected media enhancement services with real owner-supplied providers before claiming production readiness.",
  },
] satisfies ProductCapability[];
