import type { ProductCapability } from "@/lib/product/capability-types";

export const assetCapabilities = [
  {
    id: "brand-kit-basics",
    area: "assets",
    label: "Brand kit basics",
    userValue: "Brand colors, uploaded brand fonts, type presets, default logos, reusable layer looks, template defaults, and brand enforcement for selected layers are available across browser preview and desktop render handoff.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/editor/brand-kit.ts, src/lib/media/brand-font-store.ts, src/features/editor/components/brand-kit-panel.tsx, src/features/editor/components/brand-typography-panel.tsx",
    evidence: [
      "Style presets",
      "uploaded font assets",
      "Tauri font persistence",
      "native FFmpeg fontfile mapping",
      "brand typography",
      "default logos",
      "brand color defaults",
      "template defaults",
      "selected-layer brand enforcement",
    ],
    nextStep: "Verify uploaded-font desktop export in a real Tauri launch with FFmpeg installed.",
  },
  {
    id: "templates-library",
    area: "assets",
    label: "Template library",
    userValue: "Creators can use local templates, save reusable project templates, and start gaming, podcast, education, marketing, or product-demo workflows with the right canvas and export queue.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/editor/templates.ts, src/lib/editor/starter-workflows.ts, src/features/editor/components/creation-panel.tsx, src/features/editor/components/starter-workflow-panel.tsx",
    evidence: ["Search", "template categories", "project template creation", "preview metadata", "starter workflows", "canvas resize", "export queue"],
    nextStep: "Add downloadable community/template packs after cloud media storage exists.",
  },
  {
    id: "stock-media",
    area: "assets",
    label: "Stock media library",
    userValue: "Creators can search free images, video, audio, music, and sound effects in-app, import audio into a Music & SFX collection, and place music/SFX directly on the timeline.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/features/editor/components/stock-asset-browser.tsx, src/features/editor/components/media-bin.tsx, src/app/api/stock/search, src/app/api/stock/download, src/lib/stock",
    evidence: ["Free media search", "server-side safe download", "license metadata", "local media import", "music and SFX presets", "audio collection tagging", "timeline audio import"],
    nextStep: "Add user-key providers for broader commercial-safe video, music, GIF, and sound-effect catalogs.",
  },
  {
    id: "advanced-image-gif-tools",
    area: "assets",
    label: "Advanced image and GIF tools",
    userValue: "Creators can make photo collages, grids, banners, thumbnails, wallpapers, resized social images, trimmed GIFs, cropped GIFs, GIF collages, GIF-to-MP4 conversions, MP4-to-GIF exports, color-styled GIF loops, transparent GIF stickers, frame-accurate GIF trim starts, rendered source-frame thumbnail strips, and alpha-preserving layered transparent GIF exports.",
    status: "needs-verification",
    priority: "p1",
    ownerPath: "src/lib/editor/image-tool-presets.ts, src/lib/editor/gif-workflows.ts, src/lib/editor/gif-frame-preview.ts, src/lib/editor/gif-frame-thumbnails.ts, src/features/editor/components/media-layout-panel.tsx, src/features/editor/components/gif-workflow-panel.tsx",
    evidence: ["image tool presets", "GIF workflow presets", "editable media layout layers", "trim/crop/color layer patches", "conversion export queueing", "transparent GIF sticker route", "GIF frame strip", "rendered frame thumbnails", "GIF transparency route status", "transparent composite GIF frame sequence encoder"],
    nextStep: "Verify layered transparent GIF exports with real animated and overlay media in browser and desktop runtimes.",
  },
] satisfies ProductCapability[];
