import type { ProductCapability } from "@/lib/product/capability-types";

export const collaborationCapabilities = [
  {
    id: "review-qa-handoff",
    area: "collaboration",
    label: "Review and delivery QA",
    userValue: "Projects can be reviewed with notes, status, handoff summaries, pre-export QA, and comments anchored to playhead times, timeline ranges, layers, and canvas points.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/editor/delivery-qa.ts, src/lib/projects/comment-anchors.ts, src/features/projects/components/review-workspace-dialog.tsx",
    evidence: ["Review queue", "layer notes", "handoff summary", "QA checklist", "timeline range anchors", "canvas point anchors"],
    nextStep: "Add hosted public-page moderation for anchored comments.",
  },
  {
    id: "collaboration-lite",
    area: "collaboration",
    label: "Collaboration-lite",
    userValue: "Projects support anchored comments, folders, private folder metadata, local and signed-in invites, email invite drafts, project access overrides, members, share links, audit history, and workspace activity reporting.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/projects/collaboration-store.ts, src/lib/projects/server-workspace-access.ts, src/app/api/projects/[id]/access, src/features/projects/components/workspace-access-panel.tsx, src/features/projects/components/cloud-workspace-access-panel.tsx",
    evidence: [
      "Comments",
      "time anchors",
      "range anchors",
      "canvas anchors",
      "share links",
      "members",
      "invitations",
      "private folders",
      "project access overrides",
      "role permissions",
      "local audit history",
      "server-enforced access",
      "invitation acceptance links",
      "email invite drafts",
      "signed-in folder visibility",
      "workspace activity",
    ],
    nextStep: "Add optional SMTP or provider delivery after the creator configures a user-owned sending path.",
  },
  {
    id: "hosted-review-links",
    area: "collaboration",
    label: "Hosted review links",
    userValue: "Signed-in projects can create, manage, revoke, renew, and collect comments through hosted review links backed by Turso.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/projects/server-review-links.ts, src/app/api/review-links, src/app/share/[token]",
    evidence: [
      "Turso-backed link metadata",
      "permission and expiry settings",
      "public hosted review page",
      "hosted reviewer comments",
      "revoke and renew controls",
    ],
    nextStep: "Add owner-side hosted comment moderation and canvas/timeline anchors.",
  },
  {
    id: "cloud-version-history",
    area: "collaboration",
    label: "Cloud version restore and audit history",
    userValue: "Signed-in projects keep restorable Turso-backed versions and audit events when synced or restored.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/projects/server-projects.ts, src/app/api/projects/[id]/versions, src/features/dashboard/components/cloud-project-version-dialog.tsx",
    evidence: ["project_versions table", "project_audit_events table", "cloud restore dialog", "sync and restore audit events"],
    nextStep: "Add named restore points and diff summaries between versions.",
  },
  {
    id: "realtime-collaboration",
    area: "collaboration",
    label: "Safe collaboration conflicts",
    userValue: "Signed-in project sync rejects stale cloud saves, records forced overwrites, and tells creators to refresh or review versions before overwriting another edit.",
    status: "partial",
    priority: "p2",
    ownerPath: "src/lib/projects/project-sync-conflicts.ts, src/lib/projects/server-projects.ts, src/lib/projects/project-sync-client.ts",
    evidence: ["stale revision detection", "409 conflict response", "force sync audit labels", "client conflict error"],
    nextStep: "Add real-time presence and live multi-user editing after the safe conflict model is runtime-verified.",
  },
] satisfies ProductCapability[];
