import type { ProductCapability } from "@/lib/product/capability-types";

export const coreEditorCapabilities = [
  {
    id: "local-media-import",
    area: "core-editor",
    label: "Local media import",
    userValue: "Video, image, and audio files can be imported and stored locally.",
    status: "ready",
    priority: "p0",
    ownerPath: "src/features/editor/components/media-bin.tsx",
    evidence: ["Browser media store", "media validation", "missing-media recovery", "batch rename", "batch collection assign", "remove unused"],
    nextStep: "Add richer replace-file workflows and batch metadata cleanup.",
  },
  {
    id: "timeline-editing",
    area: "core-editor",
    label: "Timeline editing",
    userValue: "Creators can arrange, trim, split, group, lock, hide, and review timeline layers.",
    status: "ready",
    priority: "p0",
    ownerPath: "src/features/editor/state/editor-store.ts",
    evidence: ["Undo/redo", "trim", "split", "markers", "group-aware commands"],
    nextStep: "Split editor store into domain slices before adding transcript editing.",
  },
  {
    id: "canvas-layer-authoring",
    area: "core-editor",
    label: "Canvas and layer authoring",
    userValue: "Creators can add media, text, subtitles, shapes, stickers, overlays, and richer visual correction controls.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/features/editor/components/preview-canvas.tsx, src/features/editor/components/inspector-transform-section.tsx",
    evidence: ["Preview canvas", "inspector", "exposure", "temperature", "tint", "vignette", "motion presets", "crop aspect presets", "mask shapes", "tracking attachments"],
    nextStep: "Add richer drawn mask handles and path editing.",
  },
  {
    id: "subtitle-file-workflow",
    area: "core-editor",
    label: "Subtitle import and export",
    userValue: "Subtitle files can be imported, edited, repaired, and exported.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/subtitles",
    evidence: ["SRT/VTT import", "cue editor", "transcript export"],
    nextStep: "Add automatic speech-to-text and transcript-based timeline edits.",
  },
  {
    id: "motion-transitions",
    area: "core-editor",
    label: "Motion and transitions",
    userValue: "Motion presets, keyframes, fade, slide, push, zoom, pop, wipe transitions, reverse playback, speed ramp controls, and tracking attachments exist for timeline layers and exports.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/editor/motion.ts, src/lib/editor/keyframes.ts, src/lib/editor/transitions.ts, src/lib/editor/speed.ts, src/lib/render/native-render-graph.ts",
    evidence: ["Motion presets", "keyframe interpolation", "fade", "slide", "crossfade", "push", "zoom", "wipe", "reverse playback", "speed ramps", "native speed export filters", "tracked overlay transforms"],
    nextStep: "Add path editing and optical tracking provider adapters.",
  },
  {
    id: "transcript-editing",
    area: "core-editor",
    label: "Transcript-based editing",
    userValue: "Creators can turn transcript text matches into reviewed timeline cuts.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/subtitles/transcript-cuts.ts, src/features/editor/components/caption-transcript-tools.tsx, src/features/editor/components/inspector-panel.tsx",
    evidence: ["Transcript cut proposals", "caption cue time ranges", "cut preview list", "apply transcript cuts"],
    nextStep: "Add selection-based text deletion and richer per-cue accept/skip controls.",
  },
  {
    id: "background-object-tools",
    area: "core-editor",
    label: "Background, green screen, and object tools",
    userValue: "Creators can key out green-screen backgrounds, replace keyed areas with a chosen color, and add manual blur or solid censor masks.",
    status: "partial",
    priority: "p1",
    ownerPath: "src/lib/editor/chroma-key.ts, src/features/editor/components/visual-effects-panel.tsx, src/features/editor/components/chroma-key-preview-media.tsx",
    evidence: ["chroma key controls", "background replacement", "manual object masks", "preview canvas", "composite export alpha keying", "object-mask tracking anchors"],
    nextStep: "Add drawn mask handles, richer replacement sources, and optical object tracking.",
  },
] satisfies ProductCapability[];
