import type { ProductCapability } from "@/lib/product/capability-types";

export const exportDeliveryCapabilities = [
  {
    id: "export-queue",
    area: "export-delivery",
    label: "Export queue and project bundles",
    userValue: "Creators can queue exports, retry/cancel jobs, save project bundle backups, inspect export version metadata, and open local review pages for completed exports.",
    status: "ready",
    priority: "p0",
    ownerPath: "src/features/editor/components/export-panel.tsx, src/app/review/[reviewId]/page.tsx, src/lib/projects/collaboration-store.ts",
    evidence: ["Queue", "retry", "cancel", "bundle export", "source snapshot", "rendered file metadata", "local review page", "download history"],
    nextStep: "Add longer-project desktop rendering and richer converter workflows.",
  },
  {
    id: "social-formats",
    area: "export-delivery",
    label: "Social format variants",
    userValue: "Projects can target platform-specific LinkedIn, YouTube, Instagram, TikTok, feed, thumbnail, and banner canvases with matching safe-zone overlays.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/editor/social-format-presets.ts, src/features/editor/components/social-format-panel.tsx, src/features/editor/components/preview-canvas.tsx",
    evidence: ["Platform safe zones", "exact canvas resize", "thumbnail export", "banner export", "variant duplicate", "batch queue presets"],
    nextStep: "Add publish adapters when user-owned platform credentials are available.",
  },
  {
    id: "composite-render",
    area: "export-delivery",
    label: "Composite rendering",
    userValue: "Visual and audio layers can render through browser routes for safe timelines, while very long or layer-heavy exports are routed to the desktop renderer before browser memory becomes the bottleneck.",
    status: "needs-verification",
    priority: "p0",
    ownerPath: "src/lib/render/composite-renderer.ts, src/lib/render/render-handoff.ts, src/lib/render/native-render-adapter.ts, src-tauri/src/native_render.rs",
    evidence: ["Composite manifest", "multi-track checks", "render cleanup", "desktop render handoff", "heavy timeline budget routing", "native render adapter"],
    nextStep: "Verify representative long and layer-heavy exports inside a real desktop runtime.",
  },
  {
    id: "converter-compressor",
    area: "export-delivery",
    label: "Converter and compressor tools",
    userValue:
      "Creators can export or convert projects to MP4, WebM, MOV, AVI, MPEG, GIF, PNG, JPG, WebP, WAV, MP3, M4A, and project bundles where the browser or desktop renderer supports the route.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/features/editor/components/export-panel.tsx, src/lib/editor/presets.ts, src/lib/render/export-planner.ts, src/lib/render/browser-renderer.ts, src-tauri/src/native_ffmpeg.rs",
    evidence: [
      "target size",
      "bitrate",
      "resolution",
      "FPS",
      "caption sidecar",
      "transparent PNG",
      "JPG/WebP stills",
      "MOV/AVI/MPEG video presets",
      "MP3/M4A audio presets",
      "quality preview",
    ],
    nextStep: "Verify representative converter outputs with real media in browser and desktop runtimes.",
  },
  {
    id: "publishing-adapters",
    area: "export-delivery",
    label: "Publishing adapters",
    userValue: "Finished exports can start local review flows and create publish-prep records for YouTube, TikTok, Instagram, LinkedIn, and cloud drives with explicit user-owned credential requirements.",
    status: "partial",
    priority: "p2",
    ownerPath: "src/app/review/[reviewId]/page.tsx, src/features/review/components/publish-prep-panel.tsx, src/lib/publishing/publish-prep.ts, src/lib/projects/collaboration-store.ts",
    evidence: ["local review pages", "approval status", "comments", "download history", "publish-prep targets", "user-owned credential checklist"],
    nextStep: "Add real publish adapters only after user-owned OAuth/API credentials are configured.",
  },
] satisfies ProductCapability[];
