import type { ProductCapability } from "@/lib/product/capability-types";

export const platformCapabilities = [
  {
    id: "auth-project-metadata",
    area: "platform",
    label: "Account and project metadata",
    userValue: "Users can sign in and keep project metadata synchronized.",
    status: "ready",
    priority: "p1",
    ownerPath: "src/lib/auth, src/lib/db, src/app/api/projects",
    evidence: ["Email/password auth route", "Drizzle schema", "Project sync API"],
    nextStep: "Keep large media out of Turso while expanding optional self-hosted media adapters.",
  },
  {
    id: "local-project-dashboard",
    area: "platform",
    label: "Local project dashboard",
    userValue: "Creators can search, organize, duplicate, recover, and export local projects.",
    status: "ready",
    priority: "p0",
    ownerPath: "src/features/dashboard",
    evidence: ["Folders", "bulk actions", "snapshots", "trash recovery", "bundle export"],
    nextStep: "Split the dashboard client into smaller sections and action hooks.",
  },
  {
    id: "media-health-recovery",
    area: "platform",
    label: "Media health and recovery",
    userValue: "Missing and recoverable assets are visible before export or reopening.",
    status: "ready",
    priority: "p0",
    ownerPath: "src/lib/media/media-health.ts",
    evidence: ["Missing media impact", "recoverable status", "reconnect flow"],
    nextStep: "Add runtime smoke checks for reconnect after desktop restart.",
  },
  {
    id: "operational-readiness",
    area: "platform",
    label: "Operational readiness",
    userValue: "Creators can see project health, missing media, export failures, account availability, AI limit risks, production telemetry, and release blockers in one place.",
    status: "ready",
    priority: "p0",
    ownerPath: "src/lib/operations/operational-readiness.ts, src/lib/operations/production-telemetry.ts, src/lib/product/release-readiness.ts, src/lib/product/release-evidence.ts, src/lib/product/release-evidence-audit.ts, src/features/settings/components/operational-readiness-card.tsx, src/features/settings/components/production-telemetry-card.tsx, src/features/settings/components/release-readiness-card.tsx",
    evidence: [
      "Project health signals",
      "missing media signals",
      "export queue signals",
      "account and AI limit signals",
      "provider-neutral production telemetry",
      "release readiness gate",
      "release evidence packet",
      "release evidence packet writer",
      "release evidence packet verifier",
      "profile readiness release summary",
      "profile readiness release import",
      "upload evidence release import",
      "desktop verification release import",
      "release evidence packet import",
      "release evidence completeness summary",
      "stale release evidence detection",
      "deployment URL proof",
      "paired deployment URL and screenshot proof",
      "local deployed screenshot artifact proof",
      "desktop proof bound to ready verification history",
      "desktop evidence packet import",
      "desktop readiness evidence import",
      "desktop verification history import",
      "desktop verification history reuse",
      "deployment release preflight",
    ],
    nextStep: "Capture real desktop launch proof and deployed screenshot proof before marking release readiness complete.",
  },
  {
    id: "deployment-screenshot",
    area: "platform",
    label: "Deployment screenshot",
    userValue: "A deployed public app can be verified visually after big feature releases.",
    status: "ready",
    priority: "p0",
    ownerPath: ".vercel, src/lib/product/deployment-release-preflight.ts, scripts/write-release-evidence-packet.ts, scripts/verify-release-evidence-packet.ts",
    evidence: [
      "Deployment flow exists",
      "Deployment release preflight checklist",
      "release evidence packet writer",
      "release evidence packet verifier",
      "current Vercel account link",
      "production deployment URL",
      "node_repl screenshot artifact",
      "fresh release evidence packet",
    ],
    nextStep: "Refresh deployment and screenshot evidence after the next large feature batch.",
  },
  {
    id: "cloud-media",
    area: "platform",
    label: "Cloud media storage",
    userValue: "Creators can link CORS-enabled files from self-hosted storage so synced projects can reopen media across devices.",
    status: "ready",
    priority: "p2",
    ownerPath: "src/lib/media/self-hosted-media.ts, src/lib/media/self-hosted-upload.ts, src/lib/media/self-hosted-upload-provider-presets.ts, src/lib/media/self-hosted-upload-profiles.ts, src/lib/media/self-hosted-upload-profile-readiness.ts, src/lib/media/self-hosted-upload-history.ts, src/features/editor/components/self-hosted-media-import-dialog.tsx, src/features/editor/components/self-hosted-media-upload-dialog.tsx",
    evidence: ["Self-hosted URL media source", "URL import dialog", "signed upload handoff", "signed upload provider presets", "reusable upload profiles", "profile CORS readiness checks", "saved profile readiness history", "profile readiness evidence packet", "profile readiness release summary", "profile readiness release import", "upload verification history", "upload evidence packet", "upload evidence import", "upload evidence release import", "release readiness upload summary", "render/preflight loaders", "metadata sync schema"],
    nextStep: "Capture real desktop launch proof and deployed screenshot proof before marking release readiness complete.",
  },
] satisfies ProductCapability[];
