import {
  chart,
  chartData,
  shape,
  table,
  text,
  title,
  type TemplateConfig,
} from "./template-builders"

export const pitchTemplate: TemplateConfig<"pitch"> = {
  id: "pitch",
  name: "Startup pitch",
  deckTitle: "Startup pitch deck",
  description: "Problem, solution, market, traction, roadmap, and close.",
  accent: "#2563eb",
  slideCount: 6,
  theme: "studio",
  master: {
    showFooter: true,
    footerText: "Confidential pitch",
    showSlideNumbers: true,
    color: "#64748b",
  },
  slides: [
    {
      title: "Opening",
      sectionTitle: "Story",
      layout: "title",
      background: "#eff6ff",
      elements: [
        title("Your company changes the workflow", {
          x: 8,
          y: 19,
          width: 76,
          height: 17,
          fontSize: 40,
        }),
        text("One sentence that names the customer, pain, and promise.", {
          x: 9,
          y: 43,
          width: 58,
          height: 12,
          fontSize: 22,
          color: "#475569",
        }),
        shape({
          x: 75,
          y: 17,
          width: 12,
          height: 12,
          background: "#2563eb",
          shapeKind: "ellipse",
          shapeStrokeColor: "#1d4ed8",
        }),
      ],
    },
    {
      title: "Problem",
      layout: "title-body",
      elements: [
        title("The old process costs teams time", {
          x: 7,
          y: 9,
          width: 78,
          height: 11,
          fontSize: 34,
        }),
        text("Manual handoffs\nMissing visibility\nToo many context switches", {
          x: 8,
          y: 29,
          width: 40,
          height: 34,
          fontSize: 24,
          listStyle: "bullet",
          lineHeight: 1.35,
        }),
        shape({
          x: 56,
          y: 28,
          width: 31,
          height: 27,
          background: "#dbeafe",
          shapeKind: "rounded",
          shapeStrokeColor: "#93c5fd",
          radius: 10,
        }),
      ],
    },
    {
      title: "Solution",
      layout: "two-content",
      background: "#f8fafc",
      elements: [
        title("A focused workspace for the whole loop", {
          x: 7,
          y: 8,
          width: 78,
          height: 10,
          fontSize: 32,
        }),
        text("Capture work\nStructure decisions\nShip with history", {
          x: 8,
          y: 28,
          width: 35,
          height: 32,
          listStyle: "bullet",
          fontSize: 22,
        }),
        text("One product surface replaces three fragmented tools.", {
          x: 53,
          y: 28,
          width: 35,
          height: 32,
          fontSize: 25,
          fontWeight: 700,
          color: "#2563eb",
        }),
      ],
    },
    {
      title: "Traction",
      layout: "title-body",
      elements: [
        title("Early traction is compounding", {
          x: 7,
          y: 8,
          width: 78,
          height: 10,
          fontSize: 32,
        }),
        chart(
          chartData([
            ["Jan", 22, "#2563eb"],
            ["Feb", 37, "#16a34a"],
            ["Mar", 58, "#f97316"],
            ["Apr", 84, "#7c3aed"],
          ]),
          { x: 11, y: 25, width: 72, height: 44 },
        ),
      ],
    },
    {
      title: "Roadmap",
      layout: "title-body",
      background: "#f8fafc",
      elements: [
        title("Roadmap", { x: 7, y: 8, width: 78, height: 10, fontSize: 32 }),
        table(
          [
            "Phase",
            "Goal",
            "Timing",
            "1",
            "Private beta",
            "Now",
            "2",
            "Team launch",
            "Next",
            "3",
            "Scale channels",
            "Later",
          ],
          { x: 9, y: 25, width: 78, height: 34, tableRows: 4, tableColumns: 3 },
        ),
      ],
    },
    {
      title: "Close",
      layout: "section",
      background: "#0f172a",
      elements: [
        title("The ask", {
          x: 8,
          y: 28,
          width: 72,
          height: 14,
          fontSize: 42,
          color: "#ffffff",
          background: "transparent",
        }),
        text("What you need, by when, and what it unlocks.", {
          x: 9,
          y: 48,
          width: 62,
          height: 12,
          fontSize: 23,
          color: "#cbd5e1",
          background: "transparent",
        }),
      ],
    },
  ],
}
