export const presentationSmokeTestIds = {
  authEmailInput: "presentation-auth-email-input",
  authPanel: "presentation-auth-panel",
  authPasswordInput: "presentation-auth-password-input",
  authSubmitButton: "presentation-auth-submit-button",
  authVerificationCodeButton: "presentation-auth-verification-code-button",
  backstageDialog: "presentation-backstage-dialog",
  backstageExportRoot: "presentation-backstage-export-root",
  backstageExportTab: "presentation-backstage-export-tab",
  backstageInfoRoot: "presentation-backstage-info-root",
  backstageInfoTab: "presentation-backstage-info-tab",
  backstageRecoverRoot: "presentation-backstage-recover-root",
  backstageRecoverTab: "presentation-backstage-recover-tab",
  backstageTrigger: "presentation-backstage-trigger",
  commandPaletteDialog: "presentation-command-palette-dialog",
  commandPaletteResult: "presentation-command-palette-result",
  commandPaletteSearch: "presentation-command-palette-search",
  commandPaletteTrigger: "presentation-command-palette-trigger",
  desktopBridgeDialog: "presentation-desktop-bridge-dialog",
  desktopBridgeTrigger: "presentation-desktop-bridge-trigger",
  desktopFileHandoffPanel: "presentation-desktop-file-handoff-panel",
  desktopPackagingPanel: "presentation-desktop-packaging-panel",
  desktopReleasePanel: "presentation-desktop-release-panel",
  exportPdfButton: "presentation-export-pdf-button",
  exportPptxButton: "presentation-export-pptx-button",
  exportPreflightCopyButton: "presentation-export-preflight-copy-button",
  exportPreflightDownloadButton: "presentation-export-preflight-download-button",
  exportPreflightPanel: "presentation-export-preflight-panel",
  exportRepairLoopAction: "presentation-export-repair-loop-action",
  exportRepairLoopCopyButton: "presentation-export-repair-loop-copy-button",
  exportRepairLoopDownloadButton:
    "presentation-export-repair-loop-download-button",
  exportRepairLoopPanel: "presentation-export-repair-loop-panel",
  shareCreateLinkButton: "presentation-share-create-link-button",
  shareDialog: "presentation-share-dialog",
  shareDownloadPermissionToggle: "presentation-share-download-permission-toggle",
  shareTrigger: "presentation-share-trigger",
  statusBar: "presentation-status-bar",
  statusDeckScaleBadge: "presentation-status-deck-scale-badge",
  statusLargeDeckWindowBadge: "presentation-status-large-deck-window-badge",
  statusUndoBudgetBadge: "presentation-status-undo-budget-badge",
  workspaceDensityControls: "presentation-workspace-density-controls",
  workspaceFilmstripPanel: "presentation-workspace-filmstrip-panel",
  workspaceFilmstripToggle: "presentation-workspace-filmstrip-toggle",
  workspacePropertiesPanel: "presentation-workspace-properties-panel",
  workspacePropertiesToggle: "presentation-workspace-properties-toggle",
} as const
