import {
  getAdminCollaborationRecoveryPacketsMarkdown,
  getAdminCollaborationRecoveryPacketsReport,
} from "../src/features/admin/admin-collaboration-recovery-packets";

const report = getAdminCollaborationRecoveryPacketsReport({
  generatedAt: "2026-05-18T10:00:00.000Z",
  collaborationHandoffOperations: {
    generatedAt: "2026-05-18T09:50:00.000Z",
    status: "blocked",
    score: 64,
    roomCount: 2,
    capturedRoomCount: 2,
    activeRoomCount: 2,
    staleRoomCount: 1,
    unresolvedMentionCount: 2,
    presenterConflictCount: 1,
    presenterOwnedCount: 1,
    conflictQueueCount: 3,
    escalationQueueCount: 2,
    assignedOwnerCount: 1,
    archivedEvidenceCount: 1,
    clearedSnapshotCount: 0,
    resolvedQueueCount: 0,
    replayFreshCount: 1,
    commands: ["Export collaboration handoff rooms."],
    rooms: [
      {
        id: "room-checkout",
        status: "blocked",
        fileId: "file-checkout",
        fileName: "Checkout live review",
        ownerEmail: "sam@example.com",
        roomCaptured: true,
        roomUpdatedAt: "2026-05-18T09:40:00.000Z",
        roomAgeMinutes: 60 * 48,
        chatMessageCount: 4,
        presenceEventCount: 7,
        unresolvedMentionCount: 2,
        rawUnresolvedMentionCount: 2,
        presenter: {
          status: "conflict",
          ownerName: null,
          ownerEmail: null,
          activePresenterCount: 2,
          spotlightEventCount: 4,
          followEventCount: 1,
          replayEventCount: 5,
          lastHandoffAt: "2026-05-18T09:15:00.000Z",
          summary: "Two presenters are competing for the walkthrough.",
        },
        operationConflictCount: 2,
        targetConflictCount: 1,
        eventDriftCount: 2,
        offlineReplayQueueCount: 3,
        escalationCount: 2,
        rawEscalationCount: 4,
        latestAt: "2026-05-18T09:45:00.000Z",
        latestSignalAt: "2026-05-18T09:45:00.000Z",
        handoffOwnerName: null,
        handoffOwnerEmail: null,
        handoffAssignedAt: null,
        evidenceArchivedAt: null,
        staleSnapshotClearedAt: null,
        mentionQueueResolvedAt: null,
        escalationQueueResolvedAt: null,
        actionCount: 0,
        recommendation: "Escalate this room before release handoff.",
      },
      {
        id: "room-mobile",
        status: "ready",
        fileId: "file-mobile",
        fileName: "Mobile account settings",
        ownerEmail: "lee@example.com",
        roomCaptured: true,
        roomUpdatedAt: "2026-05-18T09:46:00.000Z",
        roomAgeMinutes: 20,
        chatMessageCount: 1,
        presenceEventCount: 3,
        unresolvedMentionCount: 0,
        rawUnresolvedMentionCount: 0,
        presenter: {
          status: "owned",
          ownerName: "Lee Editor",
          ownerEmail: "lee@example.com",
          activePresenterCount: 1,
          spotlightEventCount: 1,
          followEventCount: 3,
          replayEventCount: 4,
          lastHandoffAt: "2026-05-18T09:42:00.000Z",
          summary: "Lee owns the current walkthrough.",
        },
        operationConflictCount: 0,
        targetConflictCount: 0,
        eventDriftCount: 0,
        offlineReplayQueueCount: 0,
        escalationCount: 0,
        rawEscalationCount: 0,
        latestAt: "2026-05-18T09:48:00.000Z",
        latestSignalAt: "2026-05-18T09:48:00.000Z",
        handoffOwnerName: "Lee Editor",
        handoffOwnerEmail: "lee@example.com",
        handoffAssignedAt: "2026-05-18T09:42:00.000Z",
        evidenceArchivedAt: "2026-05-18T09:48:00.000Z",
        staleSnapshotClearedAt: null,
        mentionQueueResolvedAt: "2026-05-18T09:43:00.000Z",
        escalationQueueResolvedAt: "2026-05-18T09:44:00.000Z",
        actionCount: 3,
        recommendation: "Room handoff evidence is ready.",
      },
    ],
    rows: [],
  },
  collaborationEventIngestion: {
    generatedAt: "2026-05-18T09:52:00.000Z",
    status: "review",
    score: 80,
    durableEventCount: 20,
    redactedEventCount: 20,
    chatEventCount: 4,
    presenceEventCount: 10,
    activityEventCount: 4,
    roomActionEventCount: 2,
    incidentCount: 2,
    purgeCandidateCount: 1,
    latestPurgeAt: null,
    commands: ["Export collaboration event ingestion."],
    replayWindows: [
      {
        fileId: "file-checkout",
        fileName: "Checkout live review",
        ownerEmail: "sam@example.com",
        status: "review",
        firstEventAt: "2026-05-18T09:00:00.000Z",
        latestEventAt: "2026-05-18T09:45:00.000Z",
        retentionExpiresAt: "2026-05-25T09:45:00.000Z",
        eventCount: 14,
        chatCount: 4,
        presenceCount: 7,
        activityCount: 3,
        roomActionCount: 0,
        purgeCandidate: true,
        recommendation: "Archive evidence before purge.",
      },
      {
        fileId: "file-mobile",
        fileName: "Mobile account settings",
        ownerEmail: "lee@example.com",
        status: "ready",
        firstEventAt: "2026-05-18T09:35:00.000Z",
        latestEventAt: "2026-05-18T09:48:00.000Z",
        retentionExpiresAt: "2026-05-25T09:48:00.000Z",
        eventCount: 6,
        chatCount: 1,
        presenceCount: 3,
        activityCount: 1,
        roomActionCount: 1,
        purgeCandidate: false,
        recommendation: "Replay window is fresh.",
      },
    ],
    incidents: [],
    recentEvents: [
      {
        id: "event-activity",
        fileId: "file-checkout",
        fileName: "Checkout live review",
        ownerEmail: "sam@example.com",
        kind: "activity",
        signal: "branch-merge-conflict",
        actorRef: "participant:abcd12",
        privacy: "redacted",
        detail: "Activity replay captured a merge conflict.",
        createdAt: "2026-05-18T09:44:00.000Z",
        retentionExpiresAt: "2026-05-25T09:44:00.000Z",
      },
      {
        id: "event-chat",
        fileId: "file-checkout",
        fileName: "Checkout live review",
        ownerEmail: "sam@example.com",
        kind: "chat",
        signal: "chat-message",
        actorRef: "participant:efgh34",
        privacy: "redacted",
        detail: "Chat payload retained only as redacted length 44.",
        createdAt: "2026-05-18T09:45:00.000Z",
        retentionExpiresAt: "2026-05-25T09:45:00.000Z",
      },
    ],
  },
  multiplayerPresence: {
    generatedAt: "2026-05-18T09:54:00.000Z",
    status: "blocked",
    score: 58,
    roomCount: 2,
    activeRoomCount: 2,
    capturedRoomCount: 2,
    readyRoomCount: 1,
    reviewRoomCount: 0,
    blockedRoomCount: 1,
    presenceEventCount: 10,
    cursorEvidenceCount: 10,
    spotlightEventCount: 5,
    followEventCount: 4,
    presenterConflictCount: 1,
    presenterOwnedCount: 1,
    handoffTimerReviewCount: 1,
    staleRoomCount: 1,
    staleRecoveryQueueCount: 1,
    offlineReplayQueueCount: 3,
    eventDriftCount: 2,
    reconnectQualityScore: 62,
    saveConflictCount: 6,
    roomSaveConflictCount: 3,
    pendingSaveSignalCount: 2,
    failedSaveTelemetryCount: 1,
    durableEventCount: 20,
    purgeCandidateCount: 1,
    commands: ["Export multiplayer presence."],
    rows: [],
    rooms: [
      {
        id: "room-checkout",
        status: "blocked",
        fileId: "file-checkout",
        fileName: "Checkout live review",
        ownerEmail: "sam@example.com",
        roomCaptured: true,
        roomAgeMinutes: 60 * 48,
        chatMessageCount: 4,
        presenceEventCount: 7,
        cursorEvidenceCount: 7,
        spotlightEventCount: 4,
        followEventCount: 1,
        activePresenterCount: 2,
        presenterStatus: "conflict",
        presenterSummary: "Two presenters are competing for the walkthrough.",
        presenterHandoffAgeMinutes: 70,
        presenterHandoffTimerStatus: "blocked",
        staleRecoveryStatus: "blocked",
        offlineReplayQueueCount: 3,
        eventDriftCount: 2,
        saveConflictCount: 3,
        replayPurgeCandidate: true,
        latestAt: "2026-05-18T09:45:00.000Z",
        recommendation: "Resolve presenter conflicts and stale replay.",
      },
      {
        id: "room-mobile",
        status: "ready",
        fileId: "file-mobile",
        fileName: "Mobile account settings",
        ownerEmail: "lee@example.com",
        roomCaptured: true,
        roomAgeMinutes: 20,
        chatMessageCount: 1,
        presenceEventCount: 3,
        cursorEvidenceCount: 3,
        spotlightEventCount: 1,
        followEventCount: 3,
        activePresenterCount: 1,
        presenterStatus: "owned",
        presenterSummary: "Lee owns the current walkthrough.",
        presenterHandoffAgeMinutes: 6,
        presenterHandoffTimerStatus: "ready",
        staleRecoveryStatus: "ready",
        offlineReplayQueueCount: 0,
        eventDriftCount: 0,
        saveConflictCount: 0,
        replayPurgeCandidate: false,
        latestAt: "2026-05-18T09:48:00.000Z",
        recommendation: "Presence evidence is ready.",
      },
    ],
  },
});

assert(report.status === "blocked", "Open conflicts should block recovery packets.");
assert(report.packetCount === 2, "Every active collaboration room should get a recovery packet.");
assert(report.blockedPacketCount === 1, "Risky checkout room should be blocked.");
assert(report.readyPacketCount === 1, "Clean mobile room should be export-ready.");
assert(report.replayEvidenceCount >= 2, "Activity replay evidence should be attached.");
assert(report.ownershipHandoffCount >= 1, "Owned handoff packets should be counted.");
assert(report.conflictSummaryCount >= 1, "Conflict summaries should be attached to risky packets.");
assert(
  report.packets.some(
    (packet) =>
      packet.fileName === "Checkout live review" &&
      packet.activityReplayEvidenceCount >= 2 &&
      packet.conflictSummaryCount >= 3 &&
      packet.ownerHandoffStatus === "missing",
  ),
  "Checkout packet should include replay evidence, conflicts, and missing ownership.",
);
assert(
  report.commands.some((command) =>
    command.includes("admin:collaboration-recovery-packets-smoke"),
  ),
  "Targeted smoke command should be listed.",
);

const markdown = getAdminCollaborationRecoveryPacketsMarkdown(report);

assert(
  markdown.includes("Collaboration Recovery Packets"),
  "Markdown export should include a clear title.",
);
assert(markdown.includes("activity replay"), "Markdown should mention activity replay evidence.");
assert(markdown.includes("ownership handoff"), "Markdown should mention ownership handoff.");
assert(markdown.includes("conflict summary"), "Markdown should mention conflict summaries.");
assert(!markdown.includes("sam@example.com"), "Markdown export should redact owner emails.");

console.log(
  `Admin collaboration recovery packets smoke passed: ${report.packetCount} packets, ${report.conflictSummaryCount} conflicts.`,
);

function assert(value: unknown, message: string) {
  if (!value) {
    throw new Error(message);
  }
}
