export type VisibleControlAuditStatus = "wired" | "context-disabled";

export interface VisibleControlAuditEntry {
  id: string;
  label: string;
  ownerPath: string;
  status: VisibleControlAuditStatus;
  behavior: string;
  wiringEvidence: string[];
}

export const visibleControlAuditEntries: VisibleControlAuditEntry[] = [
  {
    id: "dashboard-continue",
    label: "Dashboard continue project",
    ownerPath: "src/features/dashboard/components/current-project-card.tsx",
    status: "wired",
    behavior: "Navigates to the active editor project.",
    wiringEvidence: ['<Link href="/editor">Continue</Link>'],
  },
  {
    id: "dashboard-preset-projects",
    label: "Dashboard preset project buttons",
    ownerPath: "src/features/dashboard/components/current-project-card.tsx",
    status: "wired",
    behavior: "Creates and opens a saved local project from the chosen aspect preset.",
    wiringEvidence: ["onCreatePresetProject", "disabled={isLibraryActionPending}"],
  },
  {
    id: "dashboard-cloud-sync",
    label: "Dashboard sync current project",
    ownerPath: "src/features/dashboard/components/current-project-card.tsx",
    status: "context-disabled",
    behavior: "Syncs project metadata when the signed-in library runtime is available.",
    wiringEvidence: ["onSyncCurrentProject", "disabled={!canUseOnlineLibrary || isCloudActionPending}"],
  },
  {
    id: "dashboard-bundle-import",
    label: "Dashboard project bundle import",
    ownerPath: "src/features/dashboard/components/local-project-library-card.tsx",
    status: "wired",
    behavior: "Opens the hidden JSON bundle input and imports a local project bundle.",
    wiringEvidence: ["bundleInputRef.current?.click()", "importBundle"],
  },
  {
    id: "dashboard-bulk-actions",
    label: "Dashboard bulk project actions",
    ownerPath: "src/features/dashboard/components/project-bulk-actions-bar.tsx",
    status: "wired",
    behavior: "Selects visible projects and runs folder, duplicate, export, or trash actions.",
    wiringEvidence: ["onAssignFolder", "onDuplicate", "onExportBundles", "onMoveToTrash"],
  },
  {
    id: "dashboard-folder-manager",
    label: "Dashboard folder manager",
    ownerPath: "src/features/dashboard/components/project-folder-manager-dialog.tsx",
    status: "wired",
    behavior: "Creates, renames, and removes project folders.",
    wiringEvidence: ["handleCreateFolder", "handleRenameFolder", "handleDeleteFolder"],
  },
  {
    id: "dashboard-trash-manager",
    label: "Dashboard trash manager",
    ownerPath: "src/features/dashboard/components/project-trash-manager-dialog.tsx",
    status: "wired",
    behavior: "Restores or permanently deletes trashed projects.",
    wiringEvidence: ['runTrashAction("restore"', 'runTrashAction("delete"'],
  },
  {
    id: "editor-local-save",
    label: "Editor local save",
    ownerPath: "src/features/projects/components/local-save-button.tsx",
    status: "wired",
    behavior: "Persists the current project and media metadata to local storage.",
    wiringEvidence: ["saveLocalProject(project, mediaAssets)", "status === \"saving\""],
  },
  {
    id: "editor-snapshot",
    label: "Editor snapshot",
    ownerPath: "src/features/projects/components/snapshot-button.tsx",
    status: "wired",
    behavior: "Creates a local project checkpoint.",
    wiringEvidence: ["createLocalProjectSnapshot(project, mediaAssets)", "status === \"saving\""],
  },
  {
    id: "editor-review-workspace",
    label: "Editor review workspace",
    ownerPath: "src/features/projects/components/review-workspace-dialog.tsx",
    status: "wired",
    behavior: "Manages comments, folders, members, and share links.",
    wiringEvidence: ["submitComment", "submitFolder", "copyShareLink"],
  },
  {
    id: "editor-playback",
    label: "Timeline play and pause",
    ownerPath: "src/features/editor/components/timeline-command-bar.tsx",
    status: "wired",
    behavior: "Toggles the editor playback clock.",
    wiringEvidence: ["onTogglePlayback", 'aria-label={isPlaying ? "Pause" : "Play"}'],
  },
  {
    id: "editor-marker-tools",
    label: "Timeline marker tools",
    ownerPath: "src/features/editor/components/timeline-command-bar.tsx",
    status: "wired",
    behavior: "Adds, edits, navigates, and removes timeline markers.",
    wiringEvidence: ["onAddMarker", "onUpdateMarker", "onRemoveMarker", "TimelineMarkerNavigation"],
  },
  {
    id: "editor-media-import",
    label: "Media import controls",
    ownerPath: "src/features/editor/components/media-bin-import-controls.tsx",
    status: "wired",
    behavior: "Imports browser files, desktop files, and reconnect files through hidden file inputs.",
    wiringEvidence: ["onFiles", "onReconnectMissingMedia", "onReconnectMissingMediaBatch", "onImportDesktopFiles"],
  },
  {
    id: "editor-media-card-actions",
    label: "Media asset card actions",
    ownerPath: "src/features/editor/components/media-asset-card.tsx",
    status: "wired",
    behavior: "Favorites, adds, reconnects, removes, previews, and files assets into collections.",
    wiringEvidence: ["onToggleFavorite", "onToggleCollection", "onAddLayer", "onStartReconnect", "onRemove"],
  },
  {
    id: "editor-recording",
    label: "Recording studio controls",
    ownerPath: "src/features/editor/components/recording-controls.tsx",
    status: "context-disabled",
    behavior: "Starts screen, camera, or voiceover recording with countdown, pause/resume, retake, and save controls.",
    wiringEvidence: [
      'startRecording("screen")',
      'startRecording("camera")',
      'startRecording("voiceover")',
      'startRecording("screen-camera")',
      "pauseRecording",
      "resumeRecording",
      "discardRecording",
      "recordingTimelinePresets.map",
      "stopRecording",
    ],
  },
  {
    id: "editor-recording-take-review",
    label: "Recording take review",
    ownerPath: "src/features/editor/components/recording-take-review.tsx",
    status: "wired",
    behavior: "Compares recorded takes and promotes the selected best take onto the timeline.",
    wiringEvidence: ["RecordingTakeReview", "TakePreview", "Best A", "Best B", "onPromoteTake"],
  },
  {
    id: "editor-ai-run",
    label: "AI assistant run",
    ownerPath: "src/features/editor/components/ai-assistant-panel.tsx",
    status: "context-disabled",
    behavior: "Runs Vercel AI SDK-backed actions when the server action runtime and prompt are available.",
    wiringEvidence: ["runAi()", "disabled={isBusy || !canRunActiveAction || !canUseOnlineActions}"],
  },
  {
    id: "editor-export",
    label: "Export and batch export",
    ownerPath: "src/features/editor/components/export-panel.tsx",
    status: "wired",
    behavior: "Runs preflight, queues exports, renders, retries, clears, and cancels export jobs.",
    wiringEvidence: ["render()", "renderBatch()", "cancelExport", "retryExport", "clearFinishedJobs"],
  },
  {
    id: "editor-caption-import",
    label: "Caption import and export controls",
    ownerPath: "src/features/editor/components/inspector-panel.tsx",
    status: "wired",
    behavior: "Imports captions and exports SRT, VTT, or transcript text.",
    wiringEvidence: ["importCaptions", "exportCaptions", "formatSrt", "formatVtt", "formatTranscript"],
  },
  {
    id: "editor-transcript-cut-preview",
    label: "Transcript cut preview",
    ownerPath: "src/features/editor/components/caption-transcript-tools.tsx",
    status: "wired",
    behavior: "Turns transcript text matches into proposed cut ranges for review.",
    wiringEvidence: ["createTranscriptCutProposals", "Preview transcript cuts", "showCutProposals"],
  },
  {
    id: "editor-media-speed",
    label: "Media speed controls",
    ownerPath: "src/features/editor/components/inspector-timing-section.tsx",
    status: "wired",
    behavior: "Updates selected media layer speed, reverse playback metadata, preserve-pitch preference, and speed ramp settings.",
    wiringEvidence: ["MediaSpeedEditor", "Speed ramp", "normalizeLayerSpeed", "onUpdateLayer"],
  },
  {
    id: "editor-creation-panel",
    label: "Creation panel templates and brand controls",
    ownerPath: "src/features/editor/components/creation-panel.tsx",
    status: "wired",
    behavior: "Applies templates, saved templates, stickers, brand colors, and safe-zone controls.",
    wiringEvidence: ["addTemplate", "addSavedTemplate", "addSticker", "applyBrandColorToSelected", "toggleSafeZones"],
  },
  {
    id: "editor-delivery-qa",
    label: "Delivery QA checklist",
    ownerPath: "src/features/editor/components/delivery-qa-checklist.tsx",
    status: "wired",
    behavior: "Shows export readiness from the delivery QA report.",
    wiringEvidence: ["createDeliveryQaReport", "DialogTrigger"],
  },
];
