/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */
export * from "./icons/icon";

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": "./icons/icon",
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Icon"
      ],
      "unused_exports": [
        "IconProps"
      ],
      "type_exports": [
        "IconProps"
      ]
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:96f2ba4d74f43c918746dd8b1ddc3f91960647d31d8dddf94050a6d3325e3835"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
