/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */
export * from "./metasearch/search-controls";
export * from "./metasearch/search-toolbar";
export * from "./ui/icon-label";
export * from "./icons/icon";

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "component",
      "name": "FrameworkCompletenessItem",
      "source": "components/launch/framework-completeness.ts",
      "import_path": "@/components/launch/framework-completeness",
      "barrel_export": null,
      "exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus",
        "frameworkCompletenessContract",
        "metasearchFrameworkCompleteness",
        "metasearchFrameworkCompletenessSummary"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus",
        "frameworkCompletenessContract",
        "metasearchFrameworkCompleteness",
        "metasearchFrameworkCompletenessSummary"
      ],
      "type_exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus"
      ]
    },
    {
      "kind": "component",
      "name": "SearchControls",
      "source": "components/metasearch/search-controls.tsx",
      "import_path": "@/components/metasearch/search-controls",
      "barrel_export": "./metasearch/search-controls",
      "exports": [
        "SearchControls"
      ],
      "default_export_name": null,
      "used_exports": [
        "SearchControls"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "SearchToolbar",
      "source": "components/metasearch/search-toolbar.tsx",
      "import_path": "@/components/metasearch/search-toolbar",
      "barrel_export": "./metasearch/search-toolbar",
      "exports": [
        "SearchToolbar"
      ],
      "default_export_name": null,
      "used_exports": [
        "SearchToolbar"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Collapse",
      "source": "components/ui/collapse.tsx",
      "import_path": "@/components/ui/collapse",
      "barrel_export": null,
      "exports": [
        "Collapse",
        "CollapseProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "Collapse",
        "CollapseProps"
      ],
      "type_exports": [
        "CollapseProps"
      ]
    },
    {
      "kind": "component",
      "name": "Dropdown",
      "source": "components/ui/dropdown.tsx",
      "import_path": "@/components/ui/dropdown",
      "barrel_export": null,
      "exports": [
        "Dropdown",
        "DropdownProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "Dropdown",
        "DropdownProps"
      ],
      "type_exports": [
        "DropdownProps"
      ]
    },
    {
      "kind": "component",
      "name": "IconLabel",
      "source": "components/ui/icon-label.tsx",
      "import_path": "@/components/ui/icon-label",
      "barrel_export": "./ui/icon-label",
      "exports": [
        "IconLabel",
        "IconLabelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "IconLabel"
      ],
      "unused_exports": [
        "IconLabelProps"
      ],
      "type_exports": [
        "IconLabelProps"
      ]
    },
    {
      "kind": "component",
      "name": "SegmentedOption",
      "source": "components/ui/segmented-select.tsx",
      "import_path": "@/components/ui/segmented-select",
      "barrel_export": null,
      "exports": [
        "SegmentedOption",
        "SegmentedSelect",
        "SegmentedSelectProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "SegmentedOption",
        "SegmentedSelect",
        "SegmentedSelectProps"
      ],
      "type_exports": [
        "SegmentedOption",
        "SegmentedSelectProps"
      ]
    },
    {
      "kind": "component",
      "name": "TextField",
      "source": "components/ui/text-field.tsx",
      "import_path": "@/components/ui/text-field",
      "barrel_export": null,
      "exports": [
        "TextField",
        "TextFieldProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "TextField",
        "TextFieldProps"
      ],
      "type_exports": [
        "TextFieldProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "ActivityIcon",
      "source": "components/icons/activity.tsx",
      "import_path": "@/components/icons/activity",
      "barrel_export": null,
      "exports": [
        "ActivityIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ActivityIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "AlertIcon",
      "source": "components/icons/alert.tsx",
      "import_path": "@/components/icons/alert",
      "barrel_export": null,
      "exports": [
        "AlertIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "AlertIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChevronDownIcon",
      "source": "components/icons/chevron-down.tsx",
      "import_path": "@/components/icons/chevron-down",
      "barrel_export": null,
      "exports": [
        "ChevronDownIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChevronDownIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "CodeIcon",
      "source": "components/icons/code.tsx",
      "import_path": "@/components/icons/code",
      "barrel_export": null,
      "exports": [
        "CodeIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "CodeIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "DetailsIcon",
      "source": "components/icons/details.tsx",
      "import_path": "@/components/icons/details",
      "barrel_export": null,
      "exports": [
        "DetailsIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "DetailsIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "EngineIcon",
      "source": "components/icons/engine.tsx",
      "import_path": "@/components/icons/engine",
      "barrel_export": null,
      "exports": [
        "EngineIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "EngineIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "FilesIcon",
      "source": "components/icons/files.tsx",
      "import_path": "@/components/icons/files",
      "barrel_export": null,
      "exports": [
        "FilesIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "FilesIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "FilterIcon",
      "source": "components/icons/filter.tsx",
      "import_path": "@/components/icons/filter",
      "barrel_export": null,
      "exports": [
        "FilterIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "FilterIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": "./icons/icon",
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Icon",
        "IconProps"
      ],
      "unused_exports": [],
      "type_exports": [
        "IconProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "ImageIcon",
      "source": "components/icons/image.tsx",
      "import_path": "@/components/icons/image",
      "barrel_export": null,
      "exports": [
        "ImageIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ImageIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "MapIcon",
      "source": "components/icons/map.tsx",
      "import_path": "@/components/icons/map",
      "barrel_export": null,
      "exports": [
        "MapIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "MapIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "MusicIcon",
      "source": "components/icons/music.tsx",
      "import_path": "@/components/icons/music",
      "barrel_export": null,
      "exports": [
        "MusicIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "MusicIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "NewsIcon",
      "source": "components/icons/news.tsx",
      "import_path": "@/components/icons/news",
      "barrel_export": null,
      "exports": [
        "NewsIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "NewsIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackageCheckIcon",
      "source": "components/icons/package-check.tsx",
      "import_path": "@/components/icons/package-check",
      "barrel_export": null,
      "exports": [
        "PackageCheckIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackageCheckIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PaletteIcon",
      "source": "components/icons/palette.tsx",
      "import_path": "@/components/icons/palette",
      "barrel_export": null,
      "exports": [
        "PaletteIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PaletteIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PlayIcon",
      "source": "components/icons/play.tsx",
      "import_path": "@/components/icons/play",
      "barrel_export": null,
      "exports": [
        "PlayIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PlayIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ScienceIcon",
      "source": "components/icons/science.tsx",
      "import_path": "@/components/icons/science",
      "barrel_export": null,
      "exports": [
        "ScienceIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ScienceIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "SearchIcon",
      "source": "components/icons/search.tsx",
      "import_path": "@/components/icons/search",
      "barrel_export": null,
      "exports": [
        "SearchIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "SearchIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ShieldIcon",
      "source": "components/icons/shield.tsx",
      "import_path": "@/components/icons/shield",
      "barrel_export": null,
      "exports": [
        "ShieldIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ShieldIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "SocialIcon",
      "source": "components/icons/social.tsx",
      "import_path": "@/components/icons/social",
      "barrel_export": null,
      "exports": [
        "SocialIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "SocialIcon"
      ],
      "type_exports": []
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:b59fb376c78ae8dbda1015c2c8bc352b72a2be091fa41124a507d3d0aa81459c"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
